# Generated by Django 4.2.30 on 2026-05-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='feedback',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='occupation',
        ),
    ]
